name: Production

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  TZ: Asia/Shanghai

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Init
      run: |
        sudo hostnamectl hostname Azure-GitHub-Actions
    - name: Checkout
      uses: actions/checkout@main
      with:
        submodules: 'true'

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cache NPM dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-cache
        restore-keys: |
          ${{ runner.OS }}-npm-cache
    - name: Build
      run: |
        make ci
        echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
    #- name: Upload to artifact
    #  uses: actions/upload-artifact@main
    #  with:
    #    name: build-${{ env.FILE_DATE }}.zip
    #    path: public

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'